#!/usr/bin/env python3
"""
generate_stats.py
------------------
اسکریپت خودمون برای ساختن کارت‌های آمار گیت‌هاب، بدون هیچ سرویس واسطه‌ی خارجی
(نه capsule-render، نه github-readme-stats). فقط مستقیم با API خود گیت‌هاب حرف می‌زنه
و دو تا فایل SVG می‌سازه که توی README لینک میشن.

خروجی:
  assets/github-stats.svg   -> تعداد ریپو، فالوور، مجموع استار، مجموع فورک
  assets/top-langs.svg      -> زبان‌های برنامه‌نویسی به تفکیک حجم کد

اجرا:
  GH_TOKEN=xxxx python scripts/generate_stats.py
(توی گیت‌هاب اکشن، GH_TOKEN خودکار از secrets.GITHUB_TOKEN پر میشه)
"""

import os
import json
import sys
from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError

USERNAME = "Mr-Hosein"
API = "https://api.github.com"
TOKEN = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")

# رنگ استاندارد هر زبان (برای رسم دایره‌ی رنگی جلوی اسمش)
LANG_COLORS = {
    "Python": "#3572A5",
    "JavaScript": "#f1e05a",
    "HTML": "#e34c26",
    "CSS": "#563d7c",
    "PHP": "#4F5D95",
    "C#": "#178600",
    "TypeScript": "#3178c6",
    "Jupyter Notebook": "#DA5B0B",
    "Shell": "#89e051",
    "Java": "#b07219",
    "C++": "#f34b7d",
    "C": "#555555",
    "Dockerfile": "#384d54",
}
DEFAULT_LANG_COLOR = "#FF3B3B"


def gh_get(path):
    """درخواست به API گیت‌هاب با احراز هویت (اگه توکن باشه)."""
    url = f"{API}{path}"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "self-hosted-stats-generator",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    req = Request(url, headers=headers)
    with urlopen(req, timeout=20) as resp:
        return json.loads(resp.read().decode())


def get_all_repos(username):
    repos = []
    page = 1
    while True:
        data = gh_get(f"/users/{username}/repos?per_page=100&page={page}&type=owner")
        if not data:
            break
        repos.extend(data)
        if len(data) < 100:
            break
        page += 1
    return repos


def collect_language_bytes(username, repos):
    totals = {}
    for repo in repos:
        if repo.get("fork"):
            continue
        try:
            langs = gh_get(f"/repos/{username}/{repo['name']}/languages")
        except (HTTPError, URLError):
            continue
        for lang, count in langs.items():
            totals[lang] = totals.get(lang, 0) + count
    return totals


def esc(text):
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


# ---------------------------------------------------------------
# ساخت SVG کارت آمار اصلی
# ---------------------------------------------------------------
def build_stats_svg(public_repos, followers, total_stars, total_forks):
    width, height = 420, 214
    stats = [
        ("Public Repos", public_repos),
        ("Followers", followers),
        ("Total Stars", total_stars),
        ("Total Forks", total_forks),
    ]

    rows = ""
    for i, (label, value) in enumerate(stats):
        y = 102 + i * 26
        rows += f'''
        <text x="28" y="{y}" font-family="JetBrains Mono, Consolas, monospace" font-size="14" fill="#8ea08b">{esc(label)}</text>
        <text x="392" y="{y}" font-family="JetBrains Mono, Consolas, monospace" font-size="14" font-weight="700" fill="#FF3B3B" text-anchor="end">{esc(value)}</text>'''

    svg = f'''<svg width="{width}" height="{height}" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">
  <rect x="1" y="1" width="{width-2}" height="{height-2}" rx="14" fill="#0D0D0D" stroke="#3a1414" stroke-width="1.5"/>

  <!-- title bar -->
  <circle cx="24" cy="24" r="5" fill="#ff5f56"/>
  <circle cx="42" cy="24" r="5" fill="#ffb454"/>
  <circle cx="60" cy="24" r="5" fill="#2ecc71"/>
  <text x="{width/2}" y="29" font-family="JetBrains Mono, Consolas, monospace" font-size="12" fill="#5c6b5a" text-anchor="middle">github --stats</text>
  <line x1="0" y1="42" x2="{width}" y2="42" stroke="#3a1414" stroke-width="1"/>

  <text x="28" y="66" font-family="JetBrains Mono, Consolas, monospace" font-size="13" fill="#FF3B3B">$ curl api.github.com/users/{USERNAME}</text>
  {rows}

  <text x="28" y="{height-16}" font-family="JetBrains Mono, Consolas, monospace" font-size="10" fill="#5c6b5a">generated by generate_stats.py • no third-party service</text>
</svg>'''
    return svg


# ---------------------------------------------------------------
# ساخت SVG کارت زبان‌های برنامه‌نویسی
# ---------------------------------------------------------------
def build_top_langs_svg(lang_bytes, top_n=6):
    width = 360
    total = sum(lang_bytes.values()) or 1
    top_langs = sorted(lang_bytes.items(), key=lambda kv: kv[1], reverse=True)[:top_n]

    row_h = 30
    height = 70 + len(top_langs) * row_h

    rows = ""
    for i, (lang, count) in enumerate(top_langs):
        pct = count / total * 100
        y = 78 + i * row_h
        color = LANG_COLORS.get(lang, DEFAULT_LANG_COLOR)
        bar_w = 190
        filled = max(2, bar_w * pct / 100)
        rows += f'''
        <circle cx="28" cy="{y-5}" r="5" fill="{color}"/>
        <text x="42" y="{y}" font-family="JetBrains Mono, Consolas, monospace" font-size="12.5" fill="#dcead8">{esc(lang)}</text>
        <text x="{width-24}" y="{y}" font-family="JetBrains Mono, Consolas, monospace" font-size="11.5" fill="#8ea08b" text-anchor="end">{pct:.1f}%</text>
        <rect x="42" y="{y+6}" width="{bar_w}" height="6" rx="3" fill="#1f2b1f"/>
        <rect x="42" y="{y+6}" width="{filled}" height="6" rx="3" fill="{color}"/>'''

    if not top_langs:
        rows = f'''<text x="28" y="80" font-family="JetBrains Mono, Consolas, monospace" font-size="12" fill="#8ea08b">no language data yet</text>'''
        height = 110

    svg = f'''<svg width="{width}" height="{height}" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">
  <rect x="1" y="1" width="{width-2}" height="{height-2}" rx="14" fill="#0D0D0D" stroke="#3a1414" stroke-width="1.5"/>

  <circle cx="24" cy="24" r="5" fill="#ff5f56"/>
  <circle cx="42" cy="24" r="5" fill="#ffb454"/>
  <circle cx="60" cy="24" r="5" fill="#2ecc71"/>
  <text x="{width/2}" y="29" font-family="JetBrains Mono, Consolas, monospace" font-size="12" fill="#5c6b5a" text-anchor="middle">top --languages</text>
  <line x1="0" y1="42" x2="{width}" y2="42" stroke="#3a1414" stroke-width="1"/>

  <text x="28" y="62" font-family="JetBrains Mono, Consolas, monospace" font-size="13" fill="#FF3B3B">$ cat languages.json</text>
  {rows}
</svg>'''
    return svg


def main():
    try:
        user = gh_get(f"/users/{USERNAME}")
        repos = get_all_repos(USERNAME)
    except (HTTPError, URLError) as e:
        print(f"GitHub API error: {e}", file=sys.stderr)
        sys.exit(1)

    public_repos = user.get("public_repos", 0)
    followers = user.get("followers", 0)
    total_stars = sum(r.get("stargazers_count", 0) for r in repos)
    total_forks = sum(r.get("forks_count", 0) for r in repos)

    lang_bytes = collect_language_bytes(USERNAME, repos)

    os.makedirs("assets", exist_ok=True)

    with open("assets/github-stats.svg", "w", encoding="utf-8") as f:
        f.write(build_stats_svg(public_repos, followers, total_stars, total_forks))

    with open("assets/top-langs.svg", "w", encoding="utf-8") as f:
        f.write(build_top_langs_svg(lang_bytes))

    print(f"OK: repos={public_repos} followers={followers} stars={total_stars} forks={total_forks} langs={len(lang_bytes)}")


if __name__ == "__main__":
    main()
